[package]
name = "esp-println"
version = "0.1.0"
edition = "2021"

[features]
default = ["uart"]

# You must enable exactly 1 of the below features to support the correct chip:
esp32   = []
esp32c3 = []
esp32s2 = []
esp32s3 = []
esp8266 = []

# You must enable exactly 1 of the below features to enable to intended
# communication method (note that "uart" is enabled by default):
uart        = []
jtag_serial = [] # C3 + S3 only!
rtt         = []
