[package]
name = "esp-println"
version = "0.1.0"
edition = "2021"

[dependencies]

[features]
esp32 = []
esp32c3 = []
esp32s2 = []
esp32s3 = []
esp8266 = []

uart = []
jtag_serial = [] # C3 + S3
rtt = []

default = [ "uart" ]
